### ISSUE TITLE
simulator iframe 被内容撑开，iframe 出现滚动条

### ISSUE THREAD

**Issue by hitao123** [youzan/vant-doc#1]
iframe 宽度无法固定，子内容宽度都是 100%，出现滚动条

**Comment by chenjiahan** [comment]
可以给下具体的复现方法嘛，我们在 vant 文档里没有碰到这个问题

**Comment by hitao123** [comment]
了解 一下vue 组件开发， 模仿了大佬的 vant， 在使用 vant-doc 使用上出了这个问题
地址 [hui](https://hitao123.github.io/hui/#/intro)

**Comment by chenjiahan** [comment]
看了下没发现啥问题喔

**Comment by hitao123** [comment]
谢谢您的耐心的解答，不过你可能没有左右拖动模拟器，底部依旧可以滑动，宽度也是给了固定宽度的
![11541752226_ pic](https://user-images.githubusercontent.com/16607714/48251575-13230400-e43d-11e8-879f-7567dd50b610.jpg)

**Comment by chenjiahan** [comment]
你在 body 上多设置了一个 min-width: 1100px; 导致的
